#!/bin/sh

mkdir -p /usr/local/lib/tracker/backup/address
rsync -a --delete /usr/local/lib/tracker/address/ /usr/local/lib/tracker/backup/address/address
pg_dump -w -U tracker initiative > /usr/local/lib/tracker/backup/address/address.dump
