#!/bin/sh

mkdir -p /var/lib/tracker/backup/address
rsync -a --delete /var/lib/tracker/address/ /var/lib/tracker/backup/address/address
pg_dump -w -U tracker initiative > /var/lib/tracker/backup/address/address.dump
