#!/bin/sh

mkdir -p /var/lib/tracker/backup/hamlog
rsync -a --delete /var/lib/tracker/hamlog/ /var/lib/tracker/backup/hamlog/hamlog
pg_dump -w -U tracker qso > /var/lib/tracker/backup/hamlog/hamlog.dump
