#!/bin/sh

mkdir -p /usr/local/lib/tracker/backup/hamlog
rsync -a --delete /usr/local/lib/tracker/hamlog/ /usr/local/lib/tracker/backup/hamlog/hamlog
pg_dump -w -U tracker qso > /usr/local/lib/tracker/backup/hamlog/hamlog.dump
