#!/bin/sh

mkdir -p /usr/local/lib/tracker/backup/time
rsync -a --delete /usr/local/lib/tracker/time/ /usr/local/lib/tracker/backup/time/time
pg_dump -w -U tracker rsctime > /usr/local/lib/tracker/backup/time/time.dump
