#!/bin/sh

mkdir -p /usr/local/lib/tracker/backup/todo
rsync -a --delete /usr/local/lib/tracker/todo/ /usr/local/lib/tracker/backup/todo/todo
pg_dump -w -U tracker todo > /usr/local/lib/tracker/backup/todo/todo.dump
