#! /usr/bin/python
# -*- coding: iso-8859-1 -*-
# Copyright (C) 2006-10 Dr. Ralf Schlatterbeck Open Source Consulting.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
#   The above copyright notice and this permission notice shall be included in
#   all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


from roundup.cgi.TranslationService import get_translation
from roundup.date                   import Date, Range
from maturity_index                 import maturity_table
try :
    from docutils.core import publish_parts
except ImportError :
    publish_parts = None

_ = None

if not publish_parts :
    def publish_parts (text, writer_name = 'html') :
        return dict (body = text)
    # end def publish_parts

def Structured_Text (text) :
    return publish_parts (text, writer_name = 'html') ['body'].replace \
        ('%', '%%').replace ('%%(', '%(')
# end def Structured_Text

date_help  = Structured_Text (Date.__doc__)
range_help = Structured_Text (Range.__doc__)

academic_title     = \
    ""'''Academic title of %(Classname)s, e.g., Dipl. Ing.'''
address_valid      = ""'''Status of this address'''
adr                = ""'Address of %(Classname)s'
adr_type_cat_code  = \
    ""'''The address type category with
         code "ABO" is special: It is used by the system for marking all
         address types that are used for marking subscribers addresses
         of running abos. Therefore the address type category with code
         "ABO" may not be deleted or changed.
      '''
city               = ""'''City where this person lives.'''
code               = ""'''Code of this %(Classname)s.'''
daily_hours        = \
    ""'''Expected daily work-time for %(Classname)s for each day of
         the week. If nothing is specified, the average of Weekly
         hours is taken. The field is mainly needed for part-time
         employees with irregular work time.
      '''
date_text          = \
    "<br><br>Ranges are used for searching dates: A range ".join \
    ((date_help, range_help))
deadline           = \
    ""'''Planned time by which this %(Classname)s should be done.'''
default_hidden     = \
    ""'''Is hidden by default except for HR and office, except if the
         user explicitly allows the number being visible.
      '''
durations          = \
    ""'''Flag if booking of durations is allowed for this %(Classname)s.'''
explicit           = \
    ""'''Only an explicitly chosen %(Property)s (or several) appear in
         the report when you also choose %(Property)s in View.
      '''
firstname          = \
    ""'''First name for this %(Classname)s, e.g., Ralf.'''
function           = \
    ""'''Multiline field for this %(Classname)s, will be printed on an
         address label
      '''
generic            = ""'''%(Property)s for this %(Classname)s'''
generic_type       = ""'''Type of %(Classname)s'''
green              = \
    ""'''Green start/end times have been created by the distribute function.'''
help_id            = \
    ""'''ID of this record, automatically generated by the system.
         Cannot be changed by the user.
      '''
invoice_amount     = \
    ""'''Amount this subscription costs'''
lastname           = \
    ""'''Last name for this %(Classname)s, e.g., Schlatterbeck'''
leave_empty        = \
    ""'''Leave this field empty if unsure.'''
keywords           = \
    ""'''Some %(Property)s for tagging -- can be useful for querying.
      '''
maturity_index_table = Structured_Text \
    ( ('=' * 20 + '  ') * 3 + '\n'
    + "%20s  %20s  %20s  \n" % ("Severity", "Status", "Value")
    + ('=' * 20 + '  ') * 3 + '\n'
    + '\n'.join
        ( "%20s  %20s  %20s  \n" % (k [0], k [1], v)
          for k, v in sorted (maturity_table.iteritems ())
        )
    + ('=' * 20 + '  ') * 3 + '\n'
    )
miss_text          = \
    ""'''If you miss an %(Property)s here, feel free to vote for it with
         an IT-Issue in category roundup.
      '''
multiple_allowed   = \
    ""'''Multiple %(Classname)s entries are allowed.'''
order              = \
    ""'''Items are ordered by this property in drop-down boxes etc.'''
priority           = \
    ""'''Priority for this %(Classname)s.'''
range_description  = \
    ""'''as a comma-separated list of ranges (a special case of a range
         is just one number), e.g., 1-100,300-500
      '''
realname_automatic = \
    ''""" -- automatically generated
         by the system from first and last name. Needed by roundup
         internally. (Roundup uses this as the sender name when
         sending messages via email)
     """
sel_wp             = \
    ""'''This selects Work packages that belong to a %(Property)s.'''
sel_tc             = \
    ""'''This selects Time categories that belong to a %(Property)s.'''
status             = \
    ""'''Status of this %(Classname)s. Automatically set on a new
         %(Classname)s if not set.
      '''
street             = ""'''Street for this %(Classname)s.'''
superseder         = \
    ""'''This %(Classname)s has been closed as a duplicate against
         another %(Classname)s.
      '''
travel             = \
    ""'''Flag to indicate travel. In the Time mask no lunchbreak will
         be computed. Even if enabled, no maximum work hours will be
         enforced for this %(Classname)s.
      '''
userdefined_name   = \
    ""'''User-defined name of this %(Classname)s'''
work_loc           = \
    ""'''Location where you worked.'''
view               = \
    ""'''The "View" selector is visible in the search form for
         %(Classname)s. Select here which columns you want to view in
         the results.
      '''
wp_no              = \
    ""'''Work package number in the project. Number must be unique for
         the project and cannot be changed after assignment.
      '''

_helptext          = \
    { ""'VIEW'                        : [view]
    , ""'abbreviation'                        :
      [""'''Abbreviated name''']
    , ""'abo'                         :
      [""'''Subscription to which this invoice belongs''']
    , ""'abo++end'                    :
      [""'''Date when this subscription ends''']
    , ""'aboprice'                    :
      [""'''Price and currency for this subscription''']
    , ""'abos'                        :
      [""'''Subscriptions for this %(Classname)s''']
    , ""'abotype'                     :
      [""'''Type of this subscription''']
    , ""'abo_type++adr_type'          :
      [ generic_type
      , ""'''-- this field indicates the address type to
             be used for marking addresses that should be exported for
             sending. When a new subsription is generated this type will
             be automatically added to the subscriber. When cancelling a
             subscription, this type will be deleted from the subscriber.
             Note that only address types can be selected here for which
             the address type category is "ABO".
          '''
      ]
    , ""'absolute'                    :
      [ ""'''For normal correction of present remaining vacation put
             in Absolute: "no". Absolute "yes" restarts vacation day
             calculation with the specified date. Is automatically set
             with 0 if new user is entered into system, is useful if
             user restarts with TTTech and rounding difference is still
             in the system. Note: Vacation correction is also possible
             if no valid dyn. user data for this date.
          '''
      ]
    , ""'achieved_hours'              :
      [""'''Achieved overtime hours included in monthly/yearly supplementary
            hours per overtime period
         '''
      ]
    , ""'active'                      :
      [""'''Set if this %(Classname)s is active.''']
    , ""'activity'                    :
      [""'''Date of last change''']
    , ""'actor'                       :
      [""'''Person who has done the last change''']
    , ""'add_announcement'            :
      [""'''Mail out an announcement for another review step''']
    , ""'add_file'                    :
      [""'''Add a new file for %(Classname)s''']
    , ""'additional_hours'            :
      [""'''Austrian-Law: time above 38.5 hours per week''']
    , ""'address'                     :
      [""'''Address for this %(Classname)s''']
    , ""'address.lookalike_city'      : [city]
    , ""'address.lookalike_firstname' : [firstname]
    , ""'address.lookalike_function'  : [function]
    , ""'address.lookalike_lastname'  : [lastname]
    , ""'address.lookalike_street'    : [street]
    , ""'address++valid'              : [address_valid]
    , ""'address++title'              : [academic_title]
    , ""'adr'                         : [adr]
    , ""'adr_type_cat.code'           : [code, adr_type_cat_code]
    , ""'adr_type_cat++code'          : [code, adr_type_cat_code]
    , ""'adr_type'                    : [generic_type]
    , ""'affix'                       :
      [""'''Name affix like e.g. "senior" or "MBA"''']
    , ""'alias'                       :
      [""'''Email alias''']
    , ""'alias_to_alias'              :
      [""'''Other aliases this %(Classname)s maps to''']
    , ""'alias_to_user'               :
      [""'''List of users this %(Classname)s maps to''']
    , ""'all_in'                      :
      [""'''If selected, the user has an all-inclusive work time contract''']
    , ""'alarm++val'                  :
      [""'''Alarm threshold value''']
    , ""'almax'                       :
      [""'''Maximum value, this or larger values trigger an alarm''']
    , ""'almin'                       :
      [""'''Minimum value, this or smaller values trigger an alarm''']
    , ""'alternate_addresses'         :
      [""'''Alternate email addresses for this user, one per line''']
    , ""'amount'                      :
      [""'''Amount payed''']
    , ""'analysis_result'             :
      [""'''Result of error analysis''']
    , ""'announcements'               :
      [""'''Announcements for this %(Classname)s''']
    , ""'approval_required'           :
      [""'''Only for absence %(Classname)s: Employee must seek approval
            via leave submission before booking.
         '''
      ]
    , ""'approval_hr'           :
      [""'''Only for absence %(Classname)s: Employee must seek approval,
            but approval may not be granted by supervisor but by a
            special HR role. This field implies
         '''
      ,  ""'''\"approval_required\".'''
      ]
    , ""'area'                        :
      [ ""'''Where this issue belongs to.'''
      , miss_text
      ]
    , ""'artefact'                    :
      [""'''Defines the detailled characteristic, e.g Project Plan,
            Manual, Specification etc.
         '''
      ]
    , ""'author'                      :
      [""'''Author of this %(Classname)s''']
    , ""'authors'                     :
      [""'''Authors of the artefact of this %(Classname)s''']
    , ""'balance'                     :
      [ ""'''Overtime balance as in staff report for the date mentioned
             in "valid on".
          '''
      ]
    , ""'balance_open'                :
      [""'''Open amount not yet payed''']
    , ""'bcc'                          :
      [ ""'''Additional emails to send to when "'''
      , ""'''send_to_customer'''
      , ""'''" flag is set.'''
      , ""''' Additional emails will not show up in mail header.'''
      ]
    , ""'begin'                       :
      [""'''Begin of period''']
    , ""'birthdate'                   :
      [""'''Date of birth for this %(Classname)s''']
    , ""'bookentry'                   :
      [""'''Date when the payment was booked''']
    , ""'bookers'                     :
      [ ""'''Users who may book on this %(Classname)s. If nothing is
             selected here, all users may book on this %(Classname)s (e.g.,
             jour fixe).
          '''
      ]
    , ""'booking_allowed'             :
      [ ""'''User is allowed to book time records during the validity span
             of the given %(Classname)s
          '''
      ]
    , ""'born'                        : [""'''Date of birth''']
    , ""'business_unit'               :
      [""'''%(Property)s responsible for this %(Classname)s''']
    , ""'card_type'                   : [""'''Type of this %(Classname)s''']
    , ""'category'                    :
      [ ""'''Category of %(Classname)s. Where this %(Classname)s belongs
             to. Each category has a Category-Responsible who is
             responsible directly after creation if not specified
             otherwise.
          '''
      , miss_text
      , leave_empty
      ]
    , ""'category++nosy'              :
      [ ""'''For new issues the %(Property)s is copied to the
             %(Property)s of the new issue
          '''
      ]
    , ""'cc'                          :
      [ ""'''Additional emails to send to when "'''
      , ""'''send_to_customer'''
      , ""'''" flag is set.'''
      ]
    , ""'cert_sw'                     :
      [ ""'''Mark this %(Classname)s as being certifyable software.
             Certifyable software needs special handling, e.g., requires that
             some fields like "Files affected" are filled in.
          '''
      ]
    , ""'city'                        : [city]
    , ""'clearance_by'                :
      [ ""'''Usually the supervisor of a person approves
             time records. This can be delegated using this attribute. It
             specifies the person who approves time records for
             all people whose supervisor this is.
          '''
      ]
    , ""'closed'                      :
      [ ""'''When this %(Classname)s was closed. Automatically set by
             Roundup.
          '''
      ]
    , ""'cls'                         :
      [ ""'''%(Classname)s class''' ]
    , ""'code'                        :
      [""'''Code of this %(Classname)s''']
    , ""'comment'                     :
      [""'''Comment for %(Classname)s''']
    , ""'comment_cancel'              :
      [""'''Comment for %(Classname)s when cancel is requested''']
    , ""'company'                     :
      [""'''Company for %(Classname)s''']
    , ""'composed_of'                 :
      [ ""'''Set automagically by roundup on %(Classname)ss being Part of
             another %(Classname)s.
          '''
      ]
    , ""'composed_of.id'              : [help_id]
    , ""'confidential'                :
      [ ""'''If set, %(Classname)s is visible only to users on the nosy
             list (note that the stakeholder and the responsible person
             are always on the nosy list).
          '''
      ]
    , ""'confirm'                     :
      [ ""'''Confirm the password here: first password and this entry
             must match.
          '''
      ]
    , ""'contact'                     :
      [ ""'''Contact information, e.g., Email address, Phone number, Fax
             number, Homepage
          '''
      ]
    , ""'contacts'                     :
      [ ""'''Contact information, e.g., Email address, Phone number...
             In order to edit a contact (e.g. phone number) please click
             on the contact type. Given the right permissions you can
             also create a new number in the row below. Deleting a
             contact is done by selecting the line in the column
             \"remove\" and then pressing \"Submit Changes\" (The
             \"remove\" columns is available only with the right
             permissions).
          '''
      ]
    , ""'contact_type'                :
      [""'''Type of contact information, e.g., Email, Phone, Fax, Homepage''']
    , ""'contact_person'              :
      [""'''Personal information about a %(Property)s''']
    , ""'content'                     : [""'''Content of %(Classname)s''']
    , ""'contract_type'               :
      [""'''%(Property)s specifies the kind of contract that
            the staff member has, like (normal) employment contract,
            separate marginal employment (in addition to the main
            employment contract), contract of work and services
            (Werkvertrag), or (AUT only) freier Dienstvertrag (social
            insurance liable free-lance contract).
      ''']
    , ""'cost_center'                 :
      [""'''%(Property)s for this %(Classname)s (required)''']
    , ""'cost_center.id'              : [help_id]
    , ""'cost_center_group.id'        : [help_id]
    , ""'cost_center_status'          :
      [""'''Specifies the Phase of this %(Classname)s item''']
    , ""'country'                     : [""'''Country for this address''']
    , ""'creation'                    : [""'''Record creation date''']
    , ""'creator'                     : [""'''Person who created this record''']
    , ""'csv_delimiter'               : [""'''Delimiter for CSV export''']
    , ""'currency'                    :
      [""'''Currency for this %(Classname)s''']
    , ""'cust_supp'                   : [""'''%(Property)s of %(Classname)s''']
    , ""'customer'                    : [""'''%(Property)s of %(Classname)s''']
    , ""'customer_status'             : [status]
    , ""'customer_type'               : [generic_type]
    , ""'customer++confidential'      :
      [""'''If this flag is set for a %(Classname)s, new support issues
            created for this %(Classname)s will be confidential.
         '''
      ]
    , ""'customer++nosy'              :
      [""'''Nosy list to use for new support issues from this
            %(Classname)s
         '''
      ]
    , ""'cut_off_date'                :
      [ ""'''Date until when this %(Classname)s must be finished.'''
      , date_text
      ]
    , ""'date'                        :
      [ ""'''Date of this %(Classname)s.<br>'''
      , date_text
      ]
    , ""'date_payed'                  :
      [""'''Date when this %(Classname)s was payed''']
    , ""'daily_hours'                 : [daily_hours]
    , ""'daily_record++weekend_allowed' :
      [ ""'''Admits user to book work or travel time on this
             weekend-day; should always be preapproved by supervisor.
          '''
      ]
    , ""'daily_record.user.id'        : [help_id]
    , ""'daily_worktime'              :
      [""'''Maximum time a person may book for a single day.''']
    , ""'defect++superseder'          :
      [superseder]
    , ""'deadline'                    :
      [deadline]
    , ""'default_lease_time'          :
      [""'''Default DHCP lease time for %(Classname)s''']
    , ""'default_nosy'                :
      [""'''If this flag is selected, a new customer created without a nosy
            list and without a nosy group will get this mail group as
            its nosy group. If several mail groups have this flag, all
            will be inherited by a new customer without specified nosy
            and nosy groups.
         '''
      ]
    , ""'default_part_of'             :
      [""'''When a new issue is created with %(Classname)s set, but
            \'Part of\' not set, then \'%(Property)s\' will be used as the
            default \'Part of\'.
         '''
      ]
    , ""'default_server'              :
      [ ""'''%(Property)s for %(Classname)s: Other DNS services may use
            the same protocol but the %(Property)s is the server of the
            company who invented the protocol. When selecting a protocol
            for use with a DNS service, the %(Property)s is used if no
            server is specified.
          '''
      ]
    , ""'department'                  :
      [""'''Department in which the %(Classname)s is based, e.g., SW, Sales.''']
    , ""'department.id'               : [help_id]
    , ""'depends'                     :
      [ ""'''A comma seperated list of %(Classname)s IDs this
             %(Classname)s depends on. This information is used for the
             planning process and should only contain the IDs of the
             issues this issue needs in order to be worked on, e.g., we
             actually need a specification before we can start to work on
             it. If you have some dependencies here, the depending
             %(Classname)ss are hyperlinked.
          '''
      ]
    , ""'depends.id'                  : [help_id]
    , ""'deputy'                      :
      [""'''Substitute for the responsible Person of %(Classname)s''']
    , ""'description'                 :
      [""'''Verbose description of %(Classname)s''']
    , ""'dev'                         :
      [ ""'''Device type name (product)''' ]
    , ""'device++adr'                 : [adr]
    , ""'device++name'                : [userdefined_name]
    , ""'device++order'               : [order]
    , ""'device_group'                :
      [ ""'''Device group for %(Classname)s -- a device may belong
             to one device group which can be configured by the user.
          '''
      ]
    , ""'dhcp_range'                  :
      [ ""'''Range of dynamic IP addresses for %(Classname)s -- used
             when generating DHCP configuration. Format: Two IP addresses in
             dot notation separated by a dot. Example:
             10.100.99.20&nbsp;10.100.99.250
          '''
      ]
    , ""'dhcp_server'                 :
      [""'''DHCP Server for this %(Classname)s''']
    , ""'display'                     :
      [ ""'''If enabled, items with %(Classname)s will be displayed
             in customer/supplier mask.
          '''
      ]
    , ""'dist'                        :
      [ ""'''Distribute: In a first step you can enter Start and End time
             for each day or the hours you worked during the day. In a
             second step you can distribute these hours to the different
             work packages you worked on during the week by entering the
             work package and the number of hours into the "Distr." field.
             The remaining hours will be distributed to your time records
             which don\'t have a work package associated.
             This mechanism works after you press "Save" and will split a
             single time record into two if necessary.
          '''
      ]
    , ""'dns_record_type'             :
      [ ""'''Type of DNS record generated. If the %(Classname)s points to
             another %(Classname)s a CNAME is generated, otherwise an
             A-record is assumed. If no DNS information should be
             generated, this field should be set to "invalid".
             This field is auto-generated if left empty.
          '''
      ]
    , ""'dns_servers'                 :
      [ ""'''DNS Servers for this %(Classname)s, used when generating
             the DHCP configuration.
          '''
      ]
    , ""'do_logging'                  :
      [""'''Log values received for this %(Classname)s''']
    , ""'do_reverse_mapping'          :
      [ ""'''Flag if a reverse DNS entry should be created for this
             %(Classname)s -- should usually be enabled. If a
             %(Classname)s has multiple A-Records (which is bad style to
             say the least) this flag must be set for only one of the
             multiple A-Records. The flag is ignored for CNAME records.
          '''
      ]
    , ""'doc++responsible'            :
      [""'''Owner of this %(Classname)s. Depending on the state, this
            shall be the author of the %(Classname)s or the reponsible
            person for review/release of the %(Classname)s.
         '''
      ]
    , ""'doc++link'                   :
      [""'''The location of the file in the repository or on the file server''']
    , ""'doc++status'                 :
      [ ""'''The status of the item. Can be one of "work in progress",
             "draft", "released" and "obsolete". The latter will cause the
             item to not be displayed in the standard query.
             For allowed transitions, see the Transistions column in the
             <a href=doc_status>Artefact Status</a> page.
          '''
      ]
    , ""'doc++title'                  :
      [ ""'''Should be an intuitive one-line description of the %(Classname)s
             consisting of the &lt;short name&gt; and the &lt;long name&gt;. 
             Example for a title:
             \"ASDM Automotive Software Development Manual\".
          '''
      ]
    , ""'doc_issue_status'            :
      [ ""'''%(Classname)s documentation status, i.e., if this
             %(Classname)s has an impact on user documentation or needs to
             be documented internally. Note that an %(Classname)s cannot
             be set to "testing" with the %(Property)s "undecided".
          '''
      ]
    , ""'doc_issue_status++nosy'      :
      [ ""'''People receiving announcements (messages) for issues with
             this %(Classname)s, the nosy list is modified when changing
             to this %(Classname)s
          '''
      ]
    , ""'doc_issue_status++order'     :
      [ order
      , ""'''Note that the %(Classname)s ordered first will also be the
             default value.
          '''
      ]
    , ""'document_nr'                 :
      [ ""'''The %(Property)s is generated when the %(Classname)s is
             created. It can be manually overwritten for an old %(Classname)s
             that already has an %(Property)s assigned.
          '''
      ]
    , ""'domain_part'                 :
      [ ""'''Part of a domain name. The domain name is built by
             concatenation the names of the Organisation and the Location.
          '''
      ]
    , ""'domino_dn'                   :
      [ ""'''Distinguished name for Domino users -- needed for alias
             generation.
          '''
      ]
    , ""'duration'                    :
      [ ""'''Work duration in hours, e.g. 7.25 -- only quarter hours
             allowed, e.g., 7.10 is not allowed. The duration is created
             automatically by the system when you specify "Start" and
             "End". Attention: If you specify both, "Start" and "Duration"
             with a duration of more than six hours, the system will
             consult your user preferences and add the lunch break, e.g.
             specifying "Start" 10:00 and "Duration" 8 will result in an
             "End" time of 18:30.
          '''
      ]
    , ""'dyndns_service'              :
      [""'''Configured %(Property)s to use for this %(Classname)s''']
    , ""'earliest_start'              :
      [ ""'''When this %(Classname)s can be started to work on. Used to
             specify external dependencies (e.g., availability of
             hardware).
          '''
      ]
    , ""'email'                       :
      [""'''Email address for this %(Classname)s''']
    , ""'email++password'             :
      [""'''SMTP password for sending alerts''']
    , ""'emails'                      :
      [""'''Customer email addresses for this %(Classname)s''']
    , ""'end'                         :
      [ ""'''Format xx:xx  (e.g. 17:00), is created automatically by the
             system when you specify "Start" and "Duration". Attention: If
             you specify both, "Start" and "End", with more than six hours
             in between, the system will consult your user preferences and
             subtract the lunch break, e.g. specifying "Start" 10:00 and
             "End" 18:00 will result in a duration of 7.5 hours (because
             half an hour lunch break was subtracted).
          '''
      , green
      ]
    , ""'external_company'            :
      [""'''Company for external users used for access control: all
            external users for a company have access if the
            %(Classname)s is on the access list for an issue
         '''
      ]
    , ""'external_ref'                :
      [""'''%(Property)s at supplier/customer for this %(Classname)s''']
    , ""'external_users'              :
      [""'''Used for access control: all
            configured external users have access to this issue -- and
            if the issue is a container to all sub-issues.
            Containers inherit the permissions of the next higher
            container only if the \'Inherit permissions\' flag is set.
         '''
      ]
    , ""'fax'                         :
      [""'''FAX number for this %(Classname)s''']
    , ""'filename_format'             :
      [""'''Naming convention for a Filename''']
    , ""'files'                       :
      [""'''Files for %(Classname)s''']
    , ""'files_affected'              :
      [ ""'''The %(Property)s entry field is used to identify which
             file(s) has/have been changed during the modifications
             requested by the current issue, containing the unique
             filename and path and the new version. The CVS output from
             the command *VCFiltered_Commit* shall be used to fill in
             this field!

             Example: Consider changed files *os_start.c*, *os_start.h*,
             and *os_version.c* in *projects/SW/external/ttpos/src/os*,
             resulting in *TTP-OS Version 4.5.23*. The entry to
             %(Property)s shall look like::

              VCupdate -r1.45 projects/SW/external/ttpos/src/os/os_start.c
              VCupdate -r1.23 projects/SW/external/ttpos/src/os/os_start.h
              VCupdate -r1.213 projects/SW/external/ttpos/src/os/os_version.c
          '''
      ]
    , ""'final_meeting_date'          :
      [ ""'''Date of final meeting for this %(Classname)s.'''
      , date_text
      ]
    , ""'first_date'                  : [ ""'''Date of first contact''']
    , ""'first_day'                   : [ ""'''First day of %(Classname)s.''']
    , ""'firstname'                   : [firstname]
    , ""'fixed_in'                    :
      [ ""'''Provide the version number where you fixed it. Is needed
             when you change the status to testing.
             The %(Property)s field contains the build version of the
             complete artefact. In the Example from Files affected the
             entry for %(Property)s shall look like::

               TTP-OS 4.5.23
          '''
      ]
    , ""'fromaddress'                 :
      [ ""'''Address in outgoing emails to which the %(Classname)s can reply.
             The email address provided must be one of the email
             addresses of the roundup tracker.
          '''
      ]
    , ""'frozen'                      :
      [ ""'''If this is set to "yes", all time records up to this date
             as well as the dynamic user data up to this date cannot be
             changed any more.
          '''
      ]
    , ""'function'                    : [function]
    , ""'fw_url'                      :
      [ ""'''Obtain IP address from IP checking page of firewall at
            %(Property)s
          '''
      ]
    , ""'fw_skip'                     :
      [ ""'''Skip any IP address before %(Property)s in output returned
            from ip-checking page of firewall
          '''
      ]
    , ""'fw_login'                    :
      [""'''%(Property)s to log into firewall''']
    , ""'fw_password'                 :
      [""'''%(Property)s to log into firewall''']
    , ""'gapint'                      :
      [""'''Sensor interval for %(Classname)s''']
    , ""'gid'                         :
      [""'''Numeric group ID''']
    , ""'gid_range'                   :
      [ ""'''Allowed range of group ids'''
      , range_description
      ]
    , ""'group'                       :
      [""'''UNIX Group for this %(Classname)s''']
    , ""'home_directory'              :
      [""'''UNIX home directory for %(Classname)s''']
    , ""'hostname'                    :
      [""'''Name of the host configured in the dynamic DNS service''']
    , ""'hours_mon'                   : [daily_hours]
    , ""'hours_tue'                   : [daily_hours]
    , ""'hours_wed'                   : [daily_hours]
    , ""'hours_thu'                   : [daily_hours]
    , ""'hours_fri'                   : [daily_hours]
    , ""'hours_sat'                   : [daily_hours]
    , ""'hours_sun'                   : [daily_hours]
    , ""'id'                          : [help_id]
    , ""'inherit_ext'                 :
      [""'''If this flag is set, and an issue is a container, it inerits
            external user permissions from the next higher-level
            container. Note that normal issues inherit the permissions
            of their container in any case.
         '''
      ]
    , ""'initial'                     :
      [""'''Initials of this %(Classname)s''']
    , ""'inreplyto'                   :
      [""'''In Reply To field if this %(Classname)s was received by email''']
    , ""'interface'                   :
      [""'''%(Property)s to determine IP address from''']
    , ""'interface_skip'              :
      [""'''Skip any IP address before %(Property)s in output of ifconfig''']
    , ""'interval'                    :
      [ ""'''Interval for sending out an invoice in months. If the
            invoice_level is non-zero, the distance in months since the
            last invoice sent.
         '''
      ]
    , ""'inventory_no'                :
      [ ""'''Unique number or name for this %(Classname)s, preferrably the
             inventory number for asset tracking
          '''
      ]
    , ""'invoice'                     :
      [""'''Link to invoice for this %(Classname)s''']
    , ""'invoice.amount'              : [invoice_amount]
    , ""'invoice++amount'             : [invoice_amount]
    , ""'invoice.payer.firstname'     : [firstname]
    , ""'invoice.payer.lastname'      : [lastname]
    , ""'invoice.payer.lookalike_city'      : [city]
    , ""'invoice.payer.lookalike_firstname' : [firstname]
    , ""'invoice.payer.lookalike_function'  : [function]
    , ""'invoice.payer.lookalike_lastname'  : [lastname]
    , ""'invoice.payer.lookalike_street'    : [street]
    , ""'invoice.payer.function'      : [function]
    , ""'invoice.payer.valid'         : [address_valid]
    , ""'invoice.subscriber.lookalike_city'      : [city]
    , ""'invoice.subscriber.lookalike_firstname' : [firstname]
    , ""'invoice.subscriber.lookalike_function'  : [function]
    , ""'invoice.subscriber.lookalike_lastname'  : [lastname]
    , ""'invoice.subscriber.lookalike_street'    : [street]
    , ""'invoice.subscriber.firstname': [firstname]
    , ""'invoice.subscriber.lastname' : [lastname]
    , ""'invoice.subscriber.valid'    : [address_valid]
    , ""'invoice_address'             :
      [""'''Data for %(Property)s''']
    , ""'invoice_group'               :
      [""'''Link to invoice_group for this %(Classname)s''']
    , ""'invoice_level'               :
      [ ""'''When the customer has received more invoices than this number
            indicates, an invoice of this type is sent.
         '''
      ]
    , ""'invoice_no'                  :
      [""'''Unique number for this invoice, generated by the system''']
    , ""'invoice_template'            :
      [""'''An OpenOffice file used as a template for this type of invoice''']
    , ""'invoices'                    :
      [""'''List of invoices for this %(Classname)s''']
    , ""'ip'                          :
      [""'''Internet protocol address of this %(Classname)s''']
    , ""'ip_subnet'                   :
      [""'''Internet protocol subnet''']
    , ""'is_alias'                    :
      [""'''No real user but only an email alias''']
    , ""'is_valid'                    :
      [""'''%(Classname)s is valid''']
    , ""'is_app_sensor'               :
      [ ""'''True if this %(Classname)s is an application sensor (not the
            battery or dBm Sensor)
          '''
      ]
    , ""'is_lotus_user'               :
      [""'''Enable this if the %(Classname)s uses Lotus Notes for mail''']
    , ""'is_actuator'                 :
      [""'''This %(Classname)s allows setting a value''']
    , ""'is_public'                   :
      [ ""'''Allow all users too book on %(Classname)s. If set, the field
             \"Admitted users\" is ignored and all users are allowed to
             book on this %(Classname)s.
          '''
      ]
    , ""'is_public_holiday'           :
      [ ""'''Flag for public holiday %(Classname)s -- set this if you
             want work packages of this %(Classname)s to be used in
             automatic public holiday computation.
          '''
      ]
    , ""'is_series'                   :
      [""'''This is turned on when the %(Classname)s is a series product''']
    , ""'is_special_leave'            :
      [""'''Set to True if %(Classname)s is for special leave:
            necessary to trigger the right email notifications and for
            special leave sum calculation.
         '''
      ]
    , ""'is_vacation'                 :
      [""'''Set to True if %(Classname)s is for vacation:
            necessary for vacation calculation.
         '''
      ]
    , ""'issue++deadline'             :
      [ deadline
      , ""'''Should only be entered on Top-Level workpackages which are
             either one single task of work or composed of one or more
             subpackages. It should definitely NOT be used to force
             dependencies of work packages (e.g. start b after a has
             finished on a given date)!!! -- This is done automatically
             by the planning tool via the Depends and Part Of fields.
          '''
      ]
    , ""'issue++title'                :
      [ ""'''Should be an intuitive one-line description of the %(Classname)s.
             Since titles of Roundup issues are also extracted into SCI
             documents, start with a capital letter, and type all other
             letters in lowercase, except names and references.
          '''
      ]
    , ""'it_issue++superseder'        :
      [superseder, multiple_allowed]
    , ""'it_prio'                     :
      [ priority
      , leave_empty
      ]
    , ""'it_project'                  :
      [""'''Optional IT Project to which this %(Classname)s belongs''']
    , ""'keyword'                     :
      [keywords]
    , ""'keywords'                    :
      [keywords]
    , ""'kind'                        :
      [ ""'''What this issue actually is. Be sure to exactly distinguish
             between what is actually a Bug (it is not working as
             expected) and a Change-Request!
             Kind "Action Item" identifies a task or activity that is
             not directly related to a product or workpackage, it is used
             for planning purpose. e.g. "Create the SRD for this
             feature"
          '''
      ]
    , ""'klass'                       :
      [""'''Class for this query''']
    , ""'last_date'                   : [ ""'''Date of last contact''']
    , ""'first_day'                   : [ ""'''Last day of %(Classname)s.''']
    , ""'last_gid'                    :
      [""'''Last used gid in this %(Classname)s''']
    , ""'last_machine_uid'            :
      [""'''Last used machine uid in this %(Classname)s''']
    , ""'last_sent'                   :
      [""'''Date when an invoice was last sent''']
    , ""'last_uid'                    :
      [""'''Last used uid in this %(Classname)s''']
    , ""'lastname'                    : [lastname]
    , ""'letter'                      :
      [""'''Download of letter -- usually this will open the letter in
           OpenOffice
        '''
      ]
    , ""'letters'                     :
      [""'''List of letters for this %(Classname)s''']
    , ""'lettertitle'                 :
      [""'''Title of this person used in a letter''']
    , ""'link_field'                  :
      [ ""'''Auxiliary field for use with other software, e.g., asset
             tracking
          '''
      ]
    , ""'local_hostname'              :
      [ ""'''Hostname of the host invoking dyndns service, currently
             defaults to localhost, there is currently no mechanism to
             configure dyndns services for remote hosts.
          '''
      ]
    , ""'location'                    :
      [""'''Location of %(Classname)s, e.g., Vienna HQ.''']
    , ""'login'                       : [generic]
    , ""'login_shell'                 :
      [""'''UNIX login shell for %(Classname)s''']
    , ""'lunch_duration'              :
      [""'''Preference for time tracking, duration of lunch break in hours''']
    , ""'lunch_start'                 :
      [""'''Preference for time tracking, start of lunch break''']
    , ""'mac'                         :
      [ ""'''MAC Address (medium access control layer) e.g. ethernet
             hardware address. Should be six hex-numbers separated by
             colons, e.g. "10:0:0:0:0:0".
          '''
      ]
    , ""'machine'                     :
      [ ""'''A machine connected to the network to which this
             %(Classname)s belongs
          '''
      ]
    , ""'machine_group'               :
      [""'''Group for pseudo-accounts for machines (used for Samba)''']
    , ""'machine_name'                :
      [""'''Link to another %(Classname)s -- converted to a CNAME.''']
    , ""'machine_uid'                 :
      [""'''Numeric user id for this samba machine.''']
    , ""'machine_uid_range'           :
      [ ""'''Allowed range of user ids for machines'''
      , range_description
      ]
    , ""'maildomain'                  :
      [""'''Mail domain of the %(Classname)s. If there is no match for
            an incoming support email, the mail domains are tried with
            the username part of the email removed. If matched, the new
            issue is associated with the customer.
         '''
      ]
    , ""'manager'                     :
      [""'''Responsible person of the %(Classname)s''']
    , ""'maturity_index'              :
      [ ""'''Maturity index for this %(Classname)s.
             Computed as follows: For a container the sum of all
             Maturity index values for all leaf nodes. For a leaf-node
             according to the following table:\n\n
          '''
      , maturity_index_table
      ]
    , ""'max_hours'                   :
      [ ""'''If given for a %(Classname)s restricts the number of hours
             you can book on this %(Classname)s for a single day.
          '''
      ]
    , ""'max_lease_time'              :
      [""'''Maximum DHCP lease time for %(Classname)s''']
    , ""'may_change_state_to'         :
      [ ""'''Allowed state changes for a given %(Classname)s: Usually
             you want to allow all states here but for some
             %(Classname)s you may want to disallow certain states, e.g.
             don\'t allow change to \"testing\".
          '''
      ]
    , ""'measurement'                 :
      [""'''Measurement for a given sensor''']
    , ""'messageid'                   :
      [""'''Message-ID if this message was received via email''']
    , ""'messages'                    :
      [ ""'''List of messages for %(Classname)s.'''
      , ""''' Note that during
             conversion from the old roundup tracker all existing
             messages numbered 1-73815 were renumbered with an offset of
             3287 resulting in the message range 3288-77102 in the
             current tracker. All messages or other documentation
             referring to message numbers in the range 1-73815 will need
             to consider this offset.
          '''
      ]
    , ""'mint'                        :
      [""'''Measurement interval for %(Classname)s''']
    , ""'msg'                         :
      [""'''New message or notice for %(Classname)s''']
    , ""'msg_keywords'                :
      [keywords]
    , ""'n_sent'                      :
      [""'''Number of times this invoice was sent''']
    , ""'name'                        :
      [""'''Unique %(Classname)s name''']
    , ""'name_version'                :
      [ ""'''Unique name of this %(Classname)s, including the version
             number
          '''
      ]
    , ""'need_msg'                    :
      [ ""'''Changing to this %(Classname)s needs a message from the
             user.
          '''
      ]
    , ""'needs.id'                    : [help_id]
    , ""'netbios_dd'                  :
      [ ""'''Netbios datagram distribution server (NBDD) option for DHCP
             config. Specifies list of servers in order of preference.
          '''
      ]
    , ""'netbios_ns'                  :
      [ ""'''Netbios name server (NBNS) option for DHCP config. Specifies
             list of servers in order of preference. Netbios name service
             is more commonly referred to as WINS.
          '''
      ]
    , ""'netbios_nodetype'            :
      [ ""'''The Netbios node type option allows NetBIOS over TCP/IP
             clients which are configurable to be configured as described
             in RFC 1001/1002. The value is specified as a single octet
             which identifies the client type. Possible types are:
             1: B-node: Broadcast - no WINS, 2: P-node: Peer - WINS only,
             4: M-node: Mixed - broadcast, then WINS, 8: H-node: Hybrid -
             WINS, then broadcast. (taken from dhcp-options manual page)
          '''
      ]
    , ""'netmask'                     :
      [""'''IP net mask for this %(Classname)s, a number (e.g., 16).''']
    , ""'network_address'             :
      [ ""'''Address in the network, including but not limited to IP
             address
          '''
      ]
    , ""'network_interface'           :
      [ ""'''Hardware unit to connect to the network. Can be part of the
             motherboard or can be a separate unit
          '''
      ]
    , ""'nickname'                    :
      [""'''Nickname (or short name) for this %(Classname)s, e.g., rsc''']
    , ""'no_overtime'                 :
      [ ""'''This flag makes sure that not more than the employee\'s
             normal working time can be registered under this
             %(Classname)s
          '''
      ]
    , ""'nosy'                        :
      [""'''People receiving announcements (messages) for %(Classname)s''']
    , ""'nosygroups'                  :
      [""'''Group(s) of nosy lists to use for new support issues from
            this %(Classname)s
         '''
      ]
    , ""'numeric_effort'              :
      [ ""'''The estimated effort this work package has. This should be
             a fair estimation done by the Responsible of the
             %(Classname)s. Be sure to set it for Change-Requests
             because otherwise one (1!) day will be used as a rough
             guess for the planning procedure -- which -- in most
             circumstances -- will NOT be sufficient. The unit is in
             person days. One person year = 10 person months, one person
             month = 4 person weeks, one person week = 5 person days.
             Note that the contents of this field will be rounded to the
             next integer, only full days make sense for the work-time
             estimates.
          '''
      ]
    , ""'op_project'                  :
      [ ""'''Flag if this %(Classname)s is a real project or just used for
             time tracking.
          '''
      ]
    , ""'open'                        :
      [ ""'''Indicates if this %(Classname)s is still open. Automatically
             maintained by the system
         '''
      ]
    , ""'opt_reviewers'               :
      [""'''Optional reviewers for this %(Classname)s''']
    , ""'order'                       : [order]
    , ""'organisation'                :
      [""'''Organisation in which the %(Classname)s is based.''']
    , ""'org_location'                :
      [ ""'''Organisation and location of this %(Classname)s, cartesian
             product of organisation and location -- only the combinations
             that really exist are stored in the database of course.
          '''
      ]
    , ""'org_location++phone'         :
      [ ""'''Telephone-Network prefix of Telephone number for company
             without direct inbound dialling suffix (aka extension)
             number
          '''
      ]
    , ""'organisation.id'             : [help_id]
    , ""'owner'                       :
      [""'''User/Owner of this %(Classname)s''']
    , ""'operating_system'            :
      [""'''Operating System running on this %(Classname)s''']
    , ""'overtime_period'             :
      [""'''Period over which overtime is computed for a person''']
    , ""'overtime_period++required_overtime' :
      [""'''Given overtime is required for the period.''']
    , ""'overtime_reduction'          :
      [""'''Don\'t count hours booked on this %(Classname)s
            for required overtime.
         '''
      ]
    , ""'parent'                      :
      [""'''%(Classname)s to which this %(Classname)s belongs.''']
    , ""'part_of'                     :
      [ ""'''If you have a Top-Level work package which consists of other
             work packages, you should enter the parent work package
             here. This information is needed for the planning process in
             order to define what %(Classname)ss compose a larger
             project, e.g., Define one Top-Level work package Some New
             Feature which is composed of Design, Build Hardware, Write
             Software, Put all parts together, and Test. In the
             search-mask you can enter
             "-1" here to find only Top-Level container work packages.
          '''
      ]
    , ""'part_of.id'                  : [help_id]
    , ""'password'                    : [generic]
    , ""'payed_abos'                  :
      [""'''Subscriptions for which this %(Classname)s is paying''']
    , ""'payer'                       :
      [""'''Address which is paying for this subscription''']
    , ""'payer.firstname'             : [firstname]
    , ""'payer.function'              : [function]
    , ""'payer.lastname'              : [lastname]
    , ""'payer.lookalike_firstname'   : [firstname]
    , ""'payer.lookalike_lastname'    : [lastname]
    , ""'payer.lookalike_function'    : [function]
    , ""'payer.valid'                 : [address_valid]
    , ""'payer.adr_type'              : [generic_type]
    , ""'payment'                     :
      [""'''Amount of payment received for this invoice''']
    , ""'peer_reviewers'              :
      [""'''Peer reviewers for this %(Classname)s''']
    , ""'period'                      :
      [""'''Subscription period in months.''']
    , ""'period_end'                  :
      [""'''Date when this invoice period ends''']
    , ""'period_start'                :
      [""'''Date when this invoice period starts''']
    , ""'person_type'                 :
      [""'''Type of this %(Classname)s for Customer/Supplier''']
    , ""'person'                      :
      [""'''personal Information for this %(Classname)s''']
    , ""'person.lookalike_firstname'  : [firstname]
    , ""'person.lookalike_function'   : [function]
    , ""'person.lookalike_lastname'   : [lastname]
    , ""'planned_effort'              :
      [ ""'''Effort for %(Classname)s in person-hours; as it is stated
             in the Project Evaluation Sheet. Warning: This used to be in
             person days, so you have to convert old values to hours!
          '''
      ]
    , ""'position'                    :
      [""'''%(Property)s in the company''']
    , ""'postalcode'                  :
      [""'''Postal code for this %(Classname)s ''']
    , ""'prio'                        :
      [ priority
      , leave_empty
      ]
    , ""'priority'                    :
      [ priority
      , ""'''Should be set between 0 and 100. For the planning process
             only issues above a specified priority level are taken into
             account. On creation of a new issue, the priority is
             automatically set to 100.
          '''
      ]
    , ""'private_for'                 :
      [""'''Flag if this is a private %(Classname)s''']
    , ""'private_gid_range'           :
      [ ""'''Allowed range of group ids for users'''
      , range_description
      ]
    , ""'prodcat'                     :
      [""'''Used for classifying products''']
    , ""'prodcat++parent'             :
      [""'''Product category which is the parent of the current product
            category
         '''
      ]
    , ""'prodcat.parent'              :
      [""'''Product category level 3''']
    , ""'prodcat.parent.parent'       :
      [""'''Product category level 2''']
    , ""'prodcat.parent.parent.parent':
      [""'''Product category level 1''']
    , ""'product'                     : [""'''%(Property)s of %(Classname)s''']
    , ""'product_family'              :
      [""'''The %(Property)s of the %(Classname)s (level 3 classification).''']
    , ""'product_use_case'            :
      [""'''The %(Property)s of the %(Classname)s (level 2 classification).''']
    , ""'product_line'                :
      [""'''The %(Property)s of the %(Classname)s (level 1 classification).''']
    , ""'product_family.id'           :
      [""'''The Id of %(Property)s.''']
    , ""'product_type'                :
      [""'''The type of the %(Classname)s.''']
    , ""'project'                     :
      [ ""'''%(Classname)s is part of a Time Category. With the Time
             Category name a
             %(Classname)s can be clearly  identified
          '''
      ]
    , ""'project_type'                :
      [""'''The %(Property)s of the %(Classname)s.''']
    , ""'project_type.id'           :
      [""'''The Id of %(Property)s.''']
    , ""'protocol'                    :
      [""'''The dynamic DNS protocol to use with this %(Classname)s.''']
    , ""'province'                    :
      [""'''Province where this person lives.''']
    , ""'qa_representative'           :
      [""'''Representative from the QA department for this %(Classname)s''']
    , ""'query++tmplate'              :
      [""'''HTML-template that is used for this %(Classname)s''']
    , ""'queries'                     :
      [""'''Queries for this %(Classname)s''']
    , ""'realname'                    :
      [""'''Real name for this %(Classname)s''', realname_automatic]
    , ""'receipt_no'                  :
      [""'''Unique identification of this payment''']
    , ""'recipients'                  :
      [""'''Only set if message was received via email.''']
    , ""'recorder'                    :
      [""'''Person responsible for recording findings''']
    , ""'reference'                   :
      [""'''Defines the relation to a project, customer, etc. If
            necessary, this entry is defined for new customers and/or
            products when the project starts.
         '''
      ]
    , ""'related_issues'              :
      [""'''Issues related to this %(Classname)s.
         '''
      ]
    , ""'related_issues.id'           : [help_id]
    , ""'relaxed'                     :
      [""'''If set, when changing status, no checks about a message, the
            priority and responsible (helpdesk) are done when changing
            to this status.
         '''
      ]
    , ""'release'                     :
      [ ""'''The %(Property)s this %(Classname)s was found, either as
             bug or as missing feature. For (newly reported) bugs,
             %(Property)s *must* be specified. Enter the release name
             or, if applicable, the name and version of the tool (e.g.,
             "TTP-Plan 4.3.72"). For change requests you may enter the
             currently used release.
          '''
      ]
    , ""'remove'                      :
      [ ""'''Remove attached item. Will not remove item from the database,
             it can usually still be downloaded via the History button.
          '''
      ]
    , ""'reporting_group'             :
      [""'''The %(Property)s of the %(Classname)s.''']
    , ""'reporting_group.id'          :
      [""'''The Id of %(Property)s.''']
    , ""'require_msg'                 :
      [""'''Require a message for this %(Classname)s''']
    , ""'require_resp_change'         :
      [""'''Require change of responsible person for this %(Classname)s''']
    , ""'required_overtime'           :
      [""'''Overtime preapproved by supervisor and required by project.''']
    , ""'responsible'                 :
      [""'''Person who is responsible for the %(Classname)s''']
    , ""'return_type'                 :
      [""'''%(Property)s for failures in the field''']
    , ""'review++responsible'         :
      [ ""'''Moderator for %(Classname)s -- Note: If you do not specify
             the moderator, you will get an indication that the field
             "Responsible" must be filled in -- the moderator is reponsible for
             %(Classname)s.
          '''
      ]
    , ""'rmafrom'                     :
      [ ""'''Address in outgoing emails to which the %(Classname)s can reply.
             The email address provided must be one of the email
             addresses of the roundup tracker.
             This address is used when the support issue in question is
             of type RMA.
          '''
      ]
    , ""'roles'                       :
      [ ""'''Roles for this %(Classname)s -- to give the user more than
             one role, enter a comma,separated,list
          '''
      ]
    , ""'room'                        :
      [""'''Room number''']
    , ""'routers'                     :
      [""'''Routers for this %(Classname)s, used in DHCP configuration.''']
    , ""'salutation'                  :
      [""'''Salutation used for printing an address''']
    , ""'samba_home_drive'            :
      [""'''Home drive for %(Classname)s in Windows''']
    , ""'samba_home_path'             :
      [""'''Path to %(Classname)ss home directory''']
    , ""'samba_kickoff_time'          :
      [""'''Windows time that user will automatically logged out''']
    , ""'samba_lm_password'           :
      [ ""'''Samba LAN Manager password -- automatically computed when a
             new password is entered
          '''
      ]
    , ""'samba_logon_script'          :
      [""'''Logon script for %(Classname)s''']
    , ""'samba_nt_password'           :
      [ ""'''Samba NT password -- automatically computed when a
             new password is entered
          '''
      ]
    , ""'samba_profile_path'          :
      [""'''Path to profile for %(Classname)s''']
    , ""'samba_pwd_can_change'        :
      [ ""'''Earliest time the user may change the password next time.
             set by the system to pwd_last_set if nothing else is enabled.
          '''
      ]
    , ""'samba_pwd_last_set'          :
      [ ""'''Time-stamp the password was last changed, automatically
             computed by the system
          '''
      ]
    , ""'samba_pwd_must_change'       :
      [ ""'''Latest time the user must change the password next time.
             set by the system to end of the epoch if nothing else is enabled.
          '''
      ]
    , ""'sap_cc'                      :
      [""'''For selecting %(Classname)s information via the %(Property)s''']
    , ""'sap_ref'                     : [""'''For tracking in SAP''']
    , ""'secondary_groups'            :
      [""'''secondary UNIX Groups for this %(Classname)s''']
    , ""'send_it'                     :
      [ ""'''Flag indicating if this invoice should be sent. If not set,
             this invoice will disappear from the current list of invoices. It
             is not sent when generating invoices and is not marked when sent
             invoices are marked.
          '''
      ]
    , ""'send_to_customer'            :
      [""'''Send to external email addresses (customer)''']
    , ""'severity'                    :
      [ ""'''How severe is the %(Classname)s for the customer or
             stakeholder
          '''
      ]
    , ""'sensor'                      :
      [ ""'''Sensor of this %(Classname)s''' ]
    , ""'sensor++adr'                 : [adr]
    , ""'sensor++name'                : [userdefined_name]
    , ""'sensor++order'               : [order]
    , ""'sensor++type'                :
      [ ""'''Type of %(Classname)s''' ]
    , ""'serial_number'               :
      [ ""'''Serial numbers of hardware items if applicable, one per line''' ]
    , ""'server'                      :
      [ ""'''The %(Property)s to use for this %(Classname)s:
            If left empty the default %(Property)s from the protocol
            configuration is used.
          '''
      ]
    , ""'shadow_last_change'          :
      [ ""'''Time-stamp the shadow password was last changed,
             automatically computed by the system
          '''
      ]
    , ""'shadow_expire'               :
      [ ""'''Date at which the users\'s account expires and will no longer
             be accessible.
          '''
      ]
    , ""'shadow_inactive'             :
      [ ""'''Number of days of inactivity after a password has expired
             before the account is locked. Note that when the password has
             expired the user is required to change it before login is
             possible. If no login occurs for a certain time, the account
             can be disabled with this setting.
          '''
      ]
    , ""'shadow_max'                  :
      [ ""'''Maximum days after last change when the shadow password must
             be changed again.
          '''
      ]
    , ""'shadow_min'                  :
      [ ""'''Minimum days after last change when the shadow password may
             be changed again.
          '''
      ]
    , ""'shadow_used'                 :
      [ ""'''Flag if shadow information should be generated, will be
             translated to LDAP shadowFlag.
          '''
      ]
    , ""'shadow_warning'              :
      [ ""'''Early warning in days before the user is required to change
             the password.
          '''
      ]
    , ""'shelf_life'                  :
      [ ""'''Shelf life in months''' ]
    , ""'shipping_address'            :
      [""'''Data for %(Property)s''']
    , ""'show_all_users'              :
      [ ""'''If this option is selected, the result will also include
             users that do not
             have a valid dynamic user record in the selected time
             range. If selected, users without a dynamic user record
             will be colored yellow for missing entries in the time
             range.
          '''
      ]
    , ""'show_empty'                  :
      [ ""'''If selected the result will also show empty records.''' ]
    , ""'show_missing'                :
      [ ""'''If this option is selected, the result will contain colored
             fields where some values may be missing. Missing values can
             result from, e.g., the user not having finished entering
             his/her time records, or the time records not yet being
             accepted by the supervisor (if you\'re searching for time
             records in category "accepted"). Note that you pay a huge
             performance penalty for this information: For each day,
             each work package and each user in the query we have to
             look for possibly missing values! So it\'s a good idea to
             only display small time-ranges with this option turned on.
          '''
      ]
    , ""'sid'                         :
      [ ""'''Samba unique ID but without the last part used for user id or
             group id information
          '''
      ]
    , ""'sint'                        :
      [""'''Transmit interval for %(Classname)s''']
    , ""'smb_domain'                  :
      [""'''Samba domain for this %(Classname)s''']
    , ""'smb_name'                    :
      [""'''Samba name for this %(Classname)s in the samba domain''']
    , ""'stakeholder'                 :
      [ ""'''Person by/for whom this %(Classname)s was raised. Usually
             defaults to the creator of the %(Classname)s, but can be
             overridden (e.g. when the IT-Department documents an issue
             that came in via telephone).
          '''
      , leave_empty
      ]
    , ""'start'                       :
      [ ""'''Format xx:xx (e.g. 09:00), defines your start of work. Has to
             be specified except for absences like e.g. holidays or sick
             leave.
          '''
      , green
      ]
    , ""'status'                      :
      [ status
      , ""'''There are constraints on status transitions.'''
      ]
    , ""'street'                      : [street]
    , ""'subject'                     :
      [""'''Short identification of %(Classname)s''']
    , ""'subscriber'                  :
      [""'''Subscriber of this subscription''']
    , ""'subscriber.lookalike_firstname' : [firstname]
    , ""'subscriber.lookalike_function'  : [function]
    , ""'subscriber.lookalike_lastname'  : [lastname]
    , ""'subscriber.firstname'        : [firstname]
    , ""'subscriber.lastname'         : [lastname]
    , ""'subscriber.function'         : [function]
    , ""'subscriber.valid'            : [address_valid]
    , ""'subscriber.adr_type'         : [generic_type]
    , ""'substitute'                  :
      [ ""'''Person who can substitute %(Classname)s for approving time
             records.
          '''
      ]
    , ""'subst_active'                :
      [ ""'''This field is set to "yes" for enabling the field
             "Substitute" for delegating time record approval.
          '''
      ]
    , ""'summary'                     :
      [""'''Short summary of this message (usually first line)''']
    , ""'summary_report++VIEW'        :
      [ view
      , ""'''The selected items are shown in the summary report; if you
             select "summary" the report gives summaries over the chosen
             summary type (e.g. weekly, monthly sums); if you select
             time category please specify which one.
          '''
      ]
    , ""'summary_report++cost_center' : [sel_tc, explicit]
    , ""'summary_report++cost_center_group' : [sel_tc, explicit]
    , ""'summary_report++date'        :
      [ ""'''please specify the date in this format:
             "YYYY-MM-DD;YYYY-MM-DD". The ";" means "to" ("bis" in
             german).  For today (heute) use ".". Example: March
             2006 is specified as "2006-03-01;2006-03-31". From the
             beginning of 2006 until now would be "2006-01-01;.". If you
             need the sum of the chosen period select Summary Type
             "range".
          '''
      ]
    , ""'summary_report++department'  :
      [ ""'''Selects the users according to their placement in a
             department
          '''
      ]
    , ""'summary_report++op_project'  :
      [ ""'''Flag to search for real-projects or a non-project (just
             used for time-tracking). Leave as don\'t care if it should
             not be searched for.
          '''
      ]
    , ""'summary_report++status'      :
      [ ""'''If you choose "open, submitted and approved" yellow times
             will be those that have not yet been opened by the user.
             Empty but already opened time records will not be displayed
             in yellow. If you choose open, all other time records
             (submitted and approved as well as not yet opened time
             records) are displayed in yellow. If you choose submitted
             all time records that are not submitted (but maybe open or
             approved) are displayed in yellow. If you choose approved
             not approved times turn yellow.
          '''
      ]
    , ""'summary_report++summary_type':
      [ ""'''You can form sums over weeks, months and the whole time
             range you have selected.
          '''
      ]
    , ""'summary_report++supervisor'  :
      [""'''Selects the users of the chosen supervisor(s)''']
    , ""'summary_report++time_project': [sel_wp, explicit]
    , ""'summary_report++time_wp'     :
      [""'''Select individual work packages here.''']
    , ""'summary_report++time_wp_group': [sel_wp, explicit]
    , ""'summary_report++user'        :
      [ ""'''You will only see users for whom you have permission or the
             project times for projects you have permission for (via
             responsible, deputy or nosy)
          '''
      ]
    , ""'superior'                    :
      [""'''Supervisor for %(Classname)s''']
    , ""'supp_per_period'           :
      [ ""'''Supplementary hours in Overtime period. If Overtime period
             is not specified, this field should be left empty.
          '''
      ]
    , ""'supp_weekly_hours'           :
      [ ""'''Weekly hours including the agreed supplementary hours (e.g.
             45h), Format: xx.xx. Please round to whole quarters of an hour
             (e.g. 0.5 means a half-hour).

             The calculation of the system "supplementary hours" -
             weekly in the staff report (independant of the number of
             hours, be it 38.5h sharp or 40 or 42 or 45 on demand) is
             not made in accordance with the daily required hours (7.75,
             Fri: 7.5) but by division through 5 over the week.
             
             E.g.
             person has 38.5h sharp system, and changes during a week to
             other system. The required hours for the days in the 38.5h
             sharp system are 7.7 per day (=38.5/5).  Inconsistencies
             occuring in the course of a change to another work-time
             system (esp. when there are paid leave times during such a
             week of change), must be repaired manually (i.e. by
             Overtime Correction).
          '''
      ]
    , ""'suppclaimfrom'               :
      [ ""'''Address in outgoing emails to which the %(Classname)s can reply.
             The email address provided must be one of the email
             addresses of the roundup tracker.
             This address is used when the support issue in question is
             of type supplier claim.
          '''
      ]
    , ""'supply_address'              :
      [""'''Data for %(Property)s''']
    , ""'support++superseder'         :
      [superseder, multiple_allowed]
    , ""'support++type'               :
      [""'Type of %(Classname)s']
    , ""'sync_with_ldap'              :
      [ ""'''Enabled if this %(Classname)s should be synched with ldap --
             when the user changes PW via PAM, the pw in roundup will be
             changed, too (if the daemon is running)
          '''
      ]
    , ""'syslog'                      :
      [""'''Enable logging to syslog''']
    , ""'target'                      :
      [ ""'''Target of this %(Classname)s, only targets explicitly
             enabled will be allowed for status changes.
          '''
      ]
    , ""'team_members'                :
      [ ""'''Persons who are assigned to the project and are allowed
             to book their effort on this project
          '''
      ]
    , ""'time_activity'               :
      [""'''Specifies the kind of work you did (e.g. meeting, ...)''']
    , ""'time_start'                  :
      [""'''Date when %(Classname)s officially starts''']
    , ""'time_end'                    :
      [""'''Date when %(Classname)s is officially closed''']
    , ""'time_project++status'        :
      [ ""'''Status of this %(Classname)s. Note that this status is only
             used for determining if new work packages may be created for
             this %(Classname)s -- it is not used during time recording
             for determining if the user may book on a work package.
          '''
      ]
    , ""'time_project++work_location' :
      [ work_loc
      , ""''' If a value is given here, the work location will be
             corrected for all time records booked on work packages of
             this project.
          '''
      ]
    , ""'time_project_status++active' :
      [ ""'''Set if this %(Classname)s is active. This determines if new
             work packages may be created for a project with this activity
             status. If a status is marked active, new work packages may
             be created for a project with this status.
          '''
      ]
    , ""'time_project.id'             : [help_id]
    , ""'time_wp++travel'             : [travel]
    , ""'time_wp.id'                  : [help_id]
    , ""'time_wp.wp_no'               : [wp_no]
    , ""'time_wp_group.id'            : [help_id]
    , ""'timeout'                     :
      [""'''Timeout when new email is sent''']
    , ""'timezone'                    :
      [""'''Time zone of this %(Classname)s -- this is a numeric hour offset''']
    , ""'title'                       :
      [ ""'''Should be an intuitive one-line description of the %(Classname)s.
          '''
      ]
    , ""'tmplate'                     :
      [ ""'''Used for writing letters (and invoices if selected as an
            invoice template)
         '''
      ]
    , ""'tmplate_status'              :
      [ ""'''Status of template -- used for letter template, invoice
             template or none.
         '''
      ]
    , ""'transceiver'                 :
      [ ""'''Transceiver on which devices are handled via radio
             connection
          '''
      ]
    , ""'transitions'                 :
      [""'''Allowed transitions to other states''']
    , ""'travel'                      :
      [ travel
      , ""''' In addition in reports the times booked will be halved (if
             exceeding the expected work hours and the person is not
             marked "travel_full" in the dynamic user data)
          '''
      ]
    , ""'tr_duration'                 :
      [ ""'''Work duration in minutes including special travel computation:
             travel times will be halved if exceeding the maximum work
             hours.
          '''
      ]
    , ""'tt_lines'                    :
      [ ""'''Number of new lines (per day) in time-tracker (minimum: 1,
             maximum: 5). This is not yet working, the logic behind it is
             not yet implemented. See also it_issue884.
          '''
      ]
    , ""'tty'                         :
      [""'''Serial line connection to transceiver''']
    , ""'type'                        :
      [""'''Mime type of this file''']
    , ""'typecat'             :
      [""'''Category of this %(Classname)s''']
    , ""'uid'                         :
      [""'''Numeric user ID''']
    , ""'uid_range'                   :
      [ ""'''Allowed range of user ids'''
      , range_description
      ]
    , ""'unit'                        :
      [""'''Unit of measurement''']
    , ""'url'                         :
      [""'''Web-Link for this %(Classname)s''']
    , ""'url_template'                :
      [ ""'''Template used when rendering the contact field for a
             contact. You can use fields of the form "%%(variable)s" to
             render variables, e.g. for a Web-Site the %(Property)s
             would be "%%(contact)s" to render the contact as a link to
             the web-site.
          '''
      ]
    , ""'use_dhcp'                    :
      [ ""'''Flag if this %(Classname)s should be served by the DHCP
             server.
          '''
      ]
    , ""'use_for_invoice'             :
      [ ""'''Flag if templates with this %(Classname)s should be visible
             in invoice templates
          '''
      ]
    , ""'use_for_letter'              :
      [ ""'''Flag if templates with this %(Classname)s should be visible
             as letter templates
          '''
      ]
    , ""'use_in_ln'                   :
      [ ""'''This %(Classname)s should be used with Lotus Notes (e.g.,
             no delivery to a program, etc. that is only possible with
             a real MTA)
          '''
      ]
    , ""'user'                        :
      [ ""'''When creating new freeze-records: Please select the user
             whose time record you want to freeze
             (with "Freeze user") or the supervisor whose team you
             want to freeze (with "Freeze team").  Freezing a team means
             freezing all users whose direct supervisor is the selected
             user at the moment. If you select a date and press "Freeze
             all", the time records of all users up to the selected date
             will be frozen.
          '''
      ]
    , ""'user_dynamic++durations_allowed' : [durations]
    , ""'user_password'               :
      [ ""'''UNIX user password, automatically set by the system when a
             new password is entered.
          '''
      ]
    , ""'user++address'               :
      [""'''Primary email address for this user''']
    , ""'user++status'                : [status]
    , ""'user++title'                 : [academic_title]
    , ""'username'                    :
      [""'''Login-name for this %(Classname)s, e.g., schlatterbeck''']
    , ""'vacation_remaining'          :
      [ ""'''Remaining vacation for this user at the start of a dynamic
             user data record.
          '''
      ]
    , ""'vacation_day'                :
      [ ""'''%(Property)s when new year for this person starts.
          '''
      ]
    , ""'vacation_month'              :
      [ ""'''%(Property)s when new year for this person starts.
          '''
      ]
    , ""'vacation_yearly'             :
      [ ""'''Yearly vacation for this user: This is the amount of vacation
             that is added for each year.
          '''
      ]
    , ""'val'                         :
      [ ""'''Measured value''' ]
    , ""'valid'                       :
      [ ""'''If enabled, this %(Classname)s is valid and can be
             selected.
          '''
      ]
    , ""'valid_from'                  :
      [ ""'''Creation date, or date since when this %(Classname)s can be
             booked at
          '''
      , date_text
      ]
    , ""'valid_to'                    :
      [ ""'''Expiration date for %(Classname)s. Note that the date given
             here is *not* itself part of the validity time.
          '''
      , date_text
      ]
    , ""'validity_date'         :
      [ ""'''Validity date of balance field. May be up to a year
             before the freeze date.
          '''
      ]
    , ""'value'                       :
      [""'''Value of this %(Classname)s''']
    , ""'visible'                     :
      [ ""''' If you set this option to "YES", all time tracker users
              can see your private %(Classname)s. If set to "No", it
              will not be accessible for the other time tracker users
              except HR and office.
          '''
      ]
    , ""'web_url'                     :
      [ ""'''Obtain IP address from IP checking page at %(Property)s
             If no method for detecting IP address is configured, this
             method is the default and uses the dyndns url (specify the
             word \"dyndns\" here to get this default).
          '''
      ]
    , ""'web_skip'                    :
      [ ""'''Skip any IP address before %(Property)s in output returned
            from website
          '''
      ]
    , ""'week'                        :
      [ ""'''Week for time tracking, this is an alternative for specifying
             a date range: just enter the week number here (for the
             current year) or YYYY/WW where YYYY is the year and WW the
             week number for that year.
          '''
      ]
    , ""'weekend_allowed'             :
      [""'''Flag if booking on weekends is allowed for this %(Classname)s.''']
    , ""'weekly_hours'                :
      [""'''Expected weekly work-time for %(Classname)s.''']
    , ""'wp'                          :
      [ ""'''Only work packages where you have permission to register show
             here. If you miss one, please contact the responsible project
             manager
          '''
      ]
    , ""'wp.id'                       : [help_id]
    , ""'wp_no'                       : [wp_no]
    , ""'wp++durations_allowed'       :
      [ durations
      , ""'''This is mainly used for special %(Classname)ss, like,
             e.g., vacation.
          '''
      ]
    , ""'wps'                         :
      [ ""'''For a better handling of the work load of a project it is
             split in to work packages. This field defines a list of work
             packages for this %(Classname)s
          '''
      ]
    , ""'wps.id'                      : [help_id]
    , ""'work_location'               : [work_loc]
    }

def combined_name (cls, attr, searchname = None) :
    """ Produce a combined name of class and attribute of the class. If
        a help-text exists for the combination, return the combination,
        otherwise return only the attribute. In this way we can override
        help-texts by specifying a help-text entry with the key
        classname++attribute. The \'searchname\' parameter is used when
        classes recursively reference attributes in other classes, e.g.,
        \'address.firstname\'.
    """
    if searchname:
        pname = '%s++%s' % (cls, searchname)
        if pname in _helptext :
            return pname
        if searchname in _helptext :
            return searchname
    pname = '%s++%s' % (cls, attr)
    if pname in _helptext :
        return pname
    return attr
# end def combined_name

def help_properties (klass) :
    """Return all class properties plus some more for which help texts
       should be displayed (e.g., "message" which describes the message
       window). The parameter klass is a html klass.
    """
    p = []
    properties = klass._klass.getprops ()
    if 'messages' in properties :
        p.append ('msg')
    if klass.classname == 'user' :
        p.append ('confirm')
    if klass.classname == 'daily_record' :
        p.append ('week')
    if klass.classname == 'file' :
        p.append (""'remove')
    if klass.classname == 'user_dynamic' :
        p.append (""'daily_hours')
    if 'announcements' in properties :
        p.append ('add_announcement')
    if 'files' in properties :
        p.append ('add_file')
    v = combined_name (klass.classname, 'VIEW')
    if v in _helptext :
        p.append (v)
    else :
        p.append ('VIEW')
    for i in properties.iterkeys () :
        pname = combined_name (klass.classname, i)
        if pname in _helptext :
            p.append (pname)
    p = [(_ (i).decode ('utf-8'), i) for i in p]
    p.sort ()
    return [i [1] for i in p]
# end def help_properties

def fieldlabel \
    ( cls
    , name
    , searchname = None
    , csscls     = 'desc'
    , startswith = ''
    , endswith   = ':'
    ) :
    if not searchname : searchname = name
    prop  = combined_name (cls, name, searchname)
    if csscls :
        csscls = 'class="%s"' % csscls
    return "<label %s>%s%s%s</label>" % (csscls, startswith, _ (prop), endswith)
# end def fieldlabel

def fieldname (cls, name, searchname = None, endswith = '&nbsp;', csscls = '') :
    if not searchname : searchname = name
    prop  = combined_name (cls, name, searchname)
    if prop not in _helptext :
        return "%s%s" % (_ (prop), endswith)
    label = _ (prop)
    href  = prop.split ('.')[-1].split ('++')[-1]
    if csscls :
        csscls = 'class="%s"' % csscls
    return (_ (''"""<a %(csscls)s title=\"Help for %(label)s\" """
               """href=\"javascript:help_window"""
               """('%(cls)s?:template=property_help#%(href)s', """
               """'500', '400')\" """
               """tabindex="-1">"""
               """%(label)s%(endswith)s</a>""" \
              ) % locals ()
           )
# end def fieldname

def helptext (key) :
    return ' '.join (_ (h) for h in _helptext [key])
# end def helptext

def permdict (perm) :
    """From a permission object compute a localized version of the dict.
       We also put a quote into the dict for the web-interface.
    """
    d = dict (perm.__dict__.iteritems ())
    d ['quote'] = '"'
    if d ['klass'] :
        d ['klass'] = _ (d ['klass'])
    if d ['properties'] :
        d ['properties'] = [_ (x) for x in d ['properties']]
    return d
# end def permdict

def set_language (client, db) :
    global _
    language = client.language
    if not language :
        language = db.config.TRACKER_LANGUAGE
    db.translator = db._db.translator = client.translator
    _ = db._db._ = db._ = db.translator.gettext
    return language
# end def set_language

def init (instance) :
    global _
    _   = get_translation \
        (instance.config.TRACKER_LANGUAGE, instance.tracker_home).gettext
    instance.registerUtil ('helptext',        helptext)
    instance.registerUtil ('help_properties', help_properties)
    instance.registerUtil ('fieldname',       fieldname)
    instance.registerUtil ('fieldlabel',      fieldlabel)
    instance.registerUtil ('combined_name',   combined_name)
    instance.registerUtil ('permdict',        permdict)
    instance.registerUtil ('set_language',    set_language)
# end def init
