#!/usr/bin/python
# -*- coding: iso-8859-1 -*-
import sys
from roundup           import instance
tracker = instance.open ('.')
db      = tracker.open ('schlatterbeck')

for id in db.contact.getnodeids () :
    # Set to something invalid. This will trigger the auditor.
    db.contact.set (id, callerid = '+')
    print db.contact.get (id, 'callerid')
db.commit ()
