#!/usr/bin/python2.4
# -*- coding: iso-8859-1 -*-
import sys
import os
from roundup           import date
from roundup           import instance
from roundup.password  import Password, encodePassword
dir     = os.getcwd ()
sys.path.insert (0, os.path.join (dir, 'lib'))
import common

tracker = instance.open (dir)
db      = tracker.open ('admin')

user = sys.argv [1]
userid = db.user.lookup (user)

wpmax  = 0
wpdict = {}

print "def import_data_%s (db, user) :" % userid
ident = '    '
for dri in db.daily_record.filter (None, dict (user = userid)) :
    dr = db.daily_record.getnode (dri)
    print ident, "dr = db.daily_record.create \\"
    print ident, "    ( user = user"
    print ident, "    , date = date.Date ('%s')" % dr.date.pretty (common.ymd)
    print ident, "    )"
    for tri in dr.time_record :
        tr = db.time_record.getnode (tri)
        print ident, "db.time_record.create \\"
        print ident, "    ( daily_record  = dr"
        print ident, "    , duration      = %s" % tr.duration
        print ident, "    , start         = %s" % tr.start
        print ident, "    , end           = %s" % tr.end
        print ident, "    , time_activity = %s" % tr.time_activity
        print ident, "    , work_location = %s" % tr.work_location
        if tr.wp not in wpdict :
            wpmax += 1
            wpdict [tr.wp] = wpmax
        print ident, "    , wp            = %s" % wpdict [tr.wp]
        print ident, "    )"
print ident, "db.commit ()"
print "# end def import_data_%s" % userid
