security = """
New Web users get the Role "User"
New Email users get the Role "User"
Role "admin":
 User may create everthing (Create)
 User may edit everthing (Edit)
 User may retire everthing (Retire)
 User may view everthing (View)
 User may access the web interface (Web Access)
 User may manipulate user Roles through the web (Web Roles)
 User may use the email interface (Email Access)
Role "adr_readonly":
 User is allowed to access adr_type (View for "adr_type" only)
 User is allowed to access adr_type_cat (View for "adr_type_cat" only)
 User is allowed to access valid (View for "valid" only)
 User is allowed to access contact_type (View for "contact_type" only)
 User is allowed to access contact (View for "contact" only)
 User is allowed to access address (View for "address" only)
 User may access the web interface (Web Access)
 User is allowed to access file (View for "file" only)
 User is allowed to access msg (View for "msg" only)
 User is allowed to access address (View for "address" only)
 User is allowed to access contact (View for "contact" only)
 User is allowed to access weekday (View for "weekday" only)
 User is allowed to access opening_hours (View for "opening_hours" only)
 User is allowed View on (View for "user": ('username', 'realname', 'phone') only)
 User is allowed to edit (some of) their own user details (Edit for "user": ('password', 'phone', 'csv_delimiter', 'timezone', 'address', 'alternate_addresses') only)
 User is allowed to view (some of) their own user details (View for "user": ('username', 'realname') only)
Role "anonymous":
 User may access the web interface (Web Access)
Role "contact":
 User is allowed to edit contact (Edit for "contact" only)
 User is allowed to create contact (Create for "contact" only)
 User is allowed to edit opening_hours (Edit for "opening_hours" only)
 User is allowed to create opening_hours (Create for "opening_hours" only)
 User is allowed to access address (View for "address" only)
 User is allowed to access contact (View for "contact" only)
 User is allowed to edit contact (Edit for "contact" only)
 User is allowed to create contact (Create for "contact" only)
 User is allowed to access weekday (View for "weekday" only)
 User is allowed to access opening_hours (View for "opening_hours" only)
Role "letter":
 User is allowed to edit tmplate (Edit for "tmplate" only)
 User is allowed to create tmplate (Create for "tmplate" only)
Role "type":
 User is allowed to edit adr_type (Edit for "adr_type" only)
 User is allowed to create adr_type (Create for "adr_type" only)
 User is allowed to edit adr_type_cat (Edit for "adr_type_cat" only)
 User is allowed to create adr_type_cat (Create for "adr_type_cat" only)
Role "user":
 User is allowed to access adr_type (View for "adr_type" only)
 User is allowed to access adr_type_cat (View for "adr_type_cat" only)
 User is allowed to access tmplate (View for "tmplate" only)
 User is allowed to access valid (View for "valid" only)
 User is allowed to access contact_type (View for "contact_type" only)
 User is allowed to access contact (View for "contact" only)
 User is allowed to access tmplate_status (View for "tmplate_status" only)
 User is allowed to access opening_hours (View for "opening_hours" only)
 User is allowed to access weekday (View for "weekday" only)
 User is allowed to access file (View for "file" only)
 User is allowed to edit file (Edit for "file" only)
 User is allowed to create file (Create for "file" only)
 User is allowed to access msg (View for "msg" only)
 User is allowed to edit msg (Edit for "msg" only)
 User is allowed to create msg (Create for "msg" only)
 User is allowed to access address (View for "address" only)
 User is allowed to edit address (Edit for "address" only)
 User is allowed to create address (Create for "address" only)
 User is allowed to access contact (View for "contact" only)
 User is allowed to access weekday (View for "weekday" only)
 User is allowed to access opening_hours (View for "opening_hours" only)
 User is allowed to edit opening_hours (Edit for "opening_hours" only)
 User is allowed to create opening_hours (Create for "opening_hours" only)
 User is allowed View on (View for "user": ('activity', 'actor', 'address', 'alternate_addresses', 'clearance_by', 'creation', 'creator', 'department', 'external_phone', 'firstname', 'job_description', 'lastname', 'lunch_duration', 'lunch_start', 'nickname', 'password', 'phone', 'pictures', 'position', 'queries', 'realname', 'room', 'sex', 'status', 'subst_active', 'substitute', 'supervisor', 'timezone', 'title', 'username', 'home_directory', 'login_shell', 'samba_home_drive', 'samba_home_path') only)
 User is allowed to edit (some of) their own user details (Edit for "user": ('password', 'phone', 'csv_delimiter', 'timezone', 'address', 'alternate_addresses') only)
 User is allowed to view (some of) their own user details (View for "user": ('username', 'realname') only)
 User is allowed to access user_status (View for "user_status" only)
 User is allowed to create file (Create for "file" only)
 User is allowed to create msg (Create for "msg" only)
 User is allowed to view their own messages (View for "msg" only)
 User is allowed to view their own files (View for "file" only)
 User is allowed View on file if file is linked from an item with View permission (View for "file" only)
 User is allowed Edit on file if file is linked from an item with Edit permission (Edit for "file" only)
 User is allowed View on msg if msg is linked from an item with View permission (View for "msg" only)
 User is allowed to view their own and public queries (View for "query" only)
 User is allowed to edit their queries (Edit for "query" only)
 User is allowed to retire their queries (Retire for "query" only)
 User is allowed to create queries (Create for "query" only)
 User may access the web interface (Web Access)
 User may use the email interface (Email Access)
""".strip ()
