security = """
New Web users get the Roles "User,Nosy"
New Email users get the Role "User"
Role "admin":
 User may access the web interface (Web Access)
 User may create everthing (Create)
 User may edit everthing (Edit)
 User may manipulate user Roles through the web (Web Roles)
 User may retire everthing (Retire)
 User may use the email interface (Email Access)
 User may view everthing (View)
Role "anonymous":
 User may access the web interface (Web Access)
Role "guest":
 User is allowed to access device (View for "device" only)
 User is allowed to access device_group (View for "device_group" only)
 User is allowed to access logstyle (View for "logstyle" only)
 User is allowed to access measurement (View for "measurement" only)
 User is allowed to access sensor (View for "sensor" only)
 User is allowed to access transceiver (View for "transceiver" only)
 User may access the web interface (Web Access)
Role "logger":
 User is allowed to access device (View for "device" only)
 User is allowed to access device_group (View for "device_group" only)
 User is allowed to access logstyle (View for "logstyle" only)
 User is allowed to access measurement (View for "measurement" only)
 User is allowed to access sensor (View for "sensor" only)
 User is allowed to access transceiver (View for "transceiver" only)
 User is allowed to create device (Create for "device" only)
 User is allowed to create measurement (Create for "measurement" only)
 User is allowed to create sensor (Create for "sensor" only)
 User is allowed to create transceiver (Create for "transceiver" only)
 User is allowed to edit device (Edit for "device" only)
 User is allowed to edit measurement (Edit for "measurement" only)
 User is allowed to edit sensor (Edit for "sensor" only)
 User is allowed to edit transceiver (Edit for "transceiver" only)
Role "user":
 User is allowed Edit on (Edit for "device": ('name', 'sint', 'mint', 'gapint', 'rec', 'device_group') only)
 User is allowed Edit on (Edit for "sensor": ('name', 'type', 'almin', 'almax', 'unit', 'do_logging') only)
 User is allowed Edit on (Edit for "transceiver": ('name', 'tty', 'sint', 'mint') only)
 User is allowed Edit on file if file is linked from an item with Edit permission (Edit for "file" only)
 User is allowed View on file if file is linked from an item with View permission (View for "file" only)
 User is allowed View on msg if msg is linked from an item with View permission (View for "msg" only)
 User is allowed to access device (View for "device" only)
 User is allowed to access device_group (View for "device_group" only)
 User is allowed to access logstyle (View for "logstyle" only)
 User is allowed to access measurement (View for "measurement" only)
 User is allowed to access sensor (View for "sensor" only)
 User is allowed to access transceiver (View for "transceiver" only)
 User is allowed to access user (View for "user" only)
 User is allowed to access user_status (View for "user_status" only)
 User is allowed to create device_group (Create for "device_group" only)
 User is allowed to create file (Create for "file" only)
 User is allowed to create msg (Create for "msg" only)
 User is allowed to create queries (Create for "query" only)
 User is allowed to edit (some of) their own user details (Edit for "user": ('csv_delimiter', 'password', 'phone', 'queries', 'realname', 'timezone') only)
 User is allowed to edit device_group (Edit for "device_group" only)
 User is allowed to edit their queries (Edit for "query" only)
 User is allowed to retire their queries (Retire for "query" only)
 User is allowed to search for their own files (Search for "file" only)
 User is allowed to search for their own messages (Search for "msg" only)
 User is allowed to search for their queries (Search for "query" only)
 User is allowed to view their own and public queries (View for "query" only)
 User is allowed to view their own files (View for "file" only)
 User is allowed to view their own messages (View for "msg" only)
 User may access the web interface (Web Access)
 User may use the email interface (Email Access)
""".strip ()
