#!/usr/bin/python
import sys
import os
from roundup           import date
from roundup           import instance
dir     = os.getcwd ()
tracker = instance.open (dir)
db      = tracker.open ('admin')

# Loop over history of procure_check and delete all items that have a
# 'link' action to pr_approval

linkdict = dict (pr_approval = True)

for id in db.pr_approval_order.getnodeids (retired = False) :
    h_old = db.getjournal ('pr_approval_order', id)
    h_new = []
    for h in h_old :
        if h [3] in ('link', 'unlink') :
            if h [4][0] in linkdict :
                continue
        h_new.append (h)
        print h_new [-1]
    if h_old != h_new :
        db.setjournal ('pr_approval_order', id, h_new)
    

db.commit()
