#!/usr/bin/python
import sys
import os
from roundup           import date
from roundup           import instance
dir     = os.getcwd ()
tracker = instance.open (dir)
db      = tracker.open ('admin')

# Get all closed TCs and loop over their WPs to determine which are
# still open: Those are closed with the current date.

tps = db.time_project_status.filter (None, dict (active = False))

now = date.Date ('.')
for tpid in db.time_project.filter (None, dict (status = tps)) :
    tp = db.time_project.getnode (tpid)
    for wpid in db.time_wp.find (project = tpid) :
        wp = db.time_wp.getnode (wpid)
        if not wp.time_end :
            print ("time_wp%s" % wpid)
            db.time_wp.set (wpid, time_end = now)

db.commit()
