#!/usr/bin/python
# -*- coding: iso-8859-1 -*-
import sys
import os
from roundup           import date
from roundup           import instance
from roundup.password  import Password, encodePassword
dir     = os.getcwd ()
tracker = instance.open (dir)
db      = tracker.open ('admin')
sys.path.insert (1, os.path.join (dir, 'lib'))
from linking import linkclass_iter

if sys.argv [1] == 'all' :
    users = {}
    d = {}
    m = 0
    for u in db.user.getnodeids () :
        x = int (u)
        d [x] = 1
        if x > m :
            m = x
    for u in range (m) :
        if u in d :
            continue
        users [u] = 1
    users = [str (x) for x in sorted (users.keys ())]
else :
    users = sys.argv [1:]

for user in users :
    print "User:", user
    for cn, prop in linkclass_iter (db, 'user') :
        cls = db.getclass (cn)
        result = cls.filter (None, {prop : user})
        if result :
            print "    Class.prop: %s.%s %s" % (cn, prop, result)
    for cl in db.getclasses () :
        db.sql \
            ( 'select * from %s__journal where tag = %s' % (cl, db.arg)
            , (user,)
            )
        for line in db.sql_fetchiter () :
            print "    journal %s: %s" % (cl, line)

