#!/usr/bin/python
import os
from roundup           import instance
dir     = os.getcwd ()
tracker = instance.open (dir)
db      = tracker.open ('admin')

for uid in db.user.getnodeids (retired = False) :
    u = db.user.getnode (uid)
    if u.position :
        pos = db.position.get (u.position, 'position')
        db.user.set (uid, position_text = pos)

db.commit()
