#!/usr/bin/python
# -*- coding: iso-8859-1 -*-
import sys
import os
from argparse          import ArgumentParser
from roundup           import date
from roundup           import instance

cmd = ArgumentParser ()
cmd.add_argument \
    ( "id"
    , help    = "ID of the item to display the history"
    )
cmd.add_argument \
    ( "-c", "--class"
    , dest    = 'cls'
    , default = 'issue'
    , help    = 'Class for the given ID, default="%(default)s"'
    )
cmd.add_argument \
    ( "-d", "--directory"
    , default = '.'
    , help    = 'Tracker directory, default="%(default)s"'
    )
args = cmd.parse_args ()

dir     = os.getcwd ()
tracker = instance.open (args.directory)
db      = tracker.open ('admin')

id    = sys.argv [1]
hist  = db.getjournal (args.cls, args.id)
for h in sorted (hist, key = lambda x : x [1], reverse = True) :
    print h
