#!/usr/bin/python
# -*- coding: iso-8859-1 -*-
import sys
import os
from roundup           import date
from roundup           import instance
dir     = os.getcwd ()
tracker = instance.open (dir)
db      = tracker.open ('admin')

antenna = db.antenna.lookup (sys.argv [1])

for n, id in enumerate (db.qso.filter (None, dict (antenna = '-1'))) :
    db.qso.set (id, antenna = antenna)
    print id

db.commit()
