#!/usr/bin/python3

import sys
sys.path.insert (1, 'utils')
import requester
urlencode = requester.urlencode

tc_org = \
    [ "1", "3", "7", "10", "20", "23", "26", "30", "34", "41", "42", "43"
     , "44", "45", "46", "47", "48", "51", "67", "68", "72", "73", "74", "75"
     , "76", "78", "80", "83", "84"
    ]
ta_org = \
    [ "4", "5", "35", "36", "37", "40", "49", "50", "52", "53", "55", "59"
     , "60", "61", "77", "79", "82"
    ]
by_company = dict (TA = ta_org, TC = tc_org)

def main (argv):
    cmd = requester.get_default_cmd (argv)
    cmd.add_argument \
        ( 'user'
        , nargs = '+'
        )
    cmd.add_argument \
        ( '-c', '--company'
        , choices  = by_company.keys ()
        , required = True
        , help     = 'Organisations the user should get'
        )
    args = cmd.parse_args ()
    rq   = requester.Requester (args)
    for u in args.user:
        # check if user in in o_permission
        o_p = rq.get ('o_permission?' + urlencode (dict (user = u)))
        o_p = o_p ['data']['collection']
        if len (o_p):
            print ('User "%s" already exists' % u)
            continue
        else:
            d = dict (user = u, org_location = by_company [args.company])
            try:
                rq.post ('o_permission', json = d)
            except RuntimeError as err:
                print (err)
                return 23
# end def main

if __name__ == '__main__':
    main (sys.argv [1:])
