#!/usr/bin/python3

import sys
import os
from roundup           import date
from roundup           import instance
dir     = os.getcwd ()
tracker = instance.open (dir)
db      = tracker.open ('admin')

tc_org = set \
    ([ '42', '32', '58', '40', '41', '51', '21', '27', '34', '59'
     , '66', '33', '50', '20', '19', '31', '45', '61', '44', '48'
     , '22', '43'
    ])
ta_org = set (['56', '39', '49', '37', '54', '47', '46', '23', '60'])

sys.path.insert (1, os.path.join (dir, 'lib'))

user_org = {}

for sid in db.sap_cc.getnodeids (retired = False):
    sap_cc = db.sap_cc.getnode (sid)
    if not sap_cc.organisation:
        continue
    for uid in (sap_cc.responsible, sap_cc.deputy):
        if not uid:
            continue
        u = db.user.getnode (uid)
        if u.status != '1':
            continue
        if uid not in user_org:
            user_org [uid] = set ()
        user_org [uid].add (sap_cc.organisation)
        print ('user%s sap_cc%s' % (uid, sid))
for pid in db.psp_element.getnodeids (retired = False):
    psp = db.psp_element.getnode (pid)
    tid = psp.project
    tc  = db.time_project.getnode (tid)
    if not tc.organisation:
        continue
    for uid in (tc.responsible, tc.deputy):
        if not uid:
            continue
        u = db.user.getnode (uid)
        if u.status != '1':
            continue
        if uid not in user_org:
            user_org [uid] = set ()
        user_org [uid].add (psp.organisation)
        print ('user%s psp%s tc%s' % (uid, pid, tid))

for uid in user_org:
    u = db.user.getnode (uid)
    print ('user%s %s' % (uid, u.username))
    orgs = user_org [uid]
    assert len (orgs) >= 1
    if len (orgs) == 1 and u.organisation == list (orgs) [0]:
        print ('    Same org')
        continue
    if u.organisation:
        orgs.add (u.organisation)
    for oid in orgs:
        org = db.organisation.getnode (oid)
        print ('    organisation%s %s' % (oid, org.name))
    if tc_org.intersection (orgs) and ta_org.intersection (orgs):
        print ('    USER IS IN BOTH ORGS')
