#!/bin/sh

TRACKER=/var/lib/tracker/address
BACKUPDIR=/var/lib/tracker/backup/address
ROUNDUP_ADMIN=/usr/local/bin/roundup-admin

### WARNING ###
### WARNING ###
### WARNING ###
# If the following is specified, an import will be done for the given
# tracker with the data exported from the tracker above. ALL DATA WILL
# BE DESTROYED in the RESTORE tracker!!!!!
# Make sure -- if you are using the same backend for the RESTORE
# tracker, that it uses a different database from the TRACKER to backup!
# This means the "name" property in the "[rdbms]" section of
# "config.ini" *must* be different for both trackers !!!
### WARNING ###
### WARNING ###
### WARNING ###
RESTORE=/var/lib/tracker/adr_restore
RESTOREPW="xyzzy"

if [ ${TRACKER} == ${RESTORE} ] ; then
    echo "READ COMMENTS. You don't want to overwrite your tracker?!"
    exit 42
fi

dir=${BACKUPDIR}/backup-$(date +%a)
echo Backing up $TRACKER to $dir
rm -rf $dir
mkdir $dir

$ROUNDUP_ADMIN -i $TRACKER export $dir
cp $TRACKER/config.ini $dir
cp $RESTORE/config.ini $dir/config.ini.restore

if [ -n "$RESTORE" ] ; then
    echo Restoring from $dir to $RESTORE
    cp $TRACKER/db/backend_name $RESTORE/db
    echo y | $ROUNDUP_ADMIN -i $RESTORE init ${RESTOREPW}
    cp $TRACKER/db/backend_name $RESTORE/db
    $ROUNDUP_ADMIN -i $RESTORE import $dir
fi

