#!/bin/sh -e
# Copyright (C) 2004-10 Dr. Ralf Schlatterbeck Open Source Consulting.
# Reichergasse 131, A-3411 Weidling.
# Web: http://www.runtux.com Email: office@runtux.com
# All rights reserved
# ****************************************************************************
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
# ****************************************************************************
# Dual License:
# If you need a proprietary license that permits you to add your own
# software without the need to publish your source-code under the GNU
# General Public License above, contact
# Reder, Christian Reder, A-2560 Berndorf, Austria, christian@reder.eu
#
# roundup	Startup script for the roundup http server.
#
# Version:	$Id: adr 6851 2009-12-18 09:58:56Z ralf $

DESC='Roundup HTTP-Server'

USER=ralf
BINFILE=roundup-server 
EXECUTABLE=/usr/local/bin/$BINFILE
ROOTBIN=update_handler
LIELAS_PATH=/home/ralf/roundup/lielas2
RUNDIR=$LIELAS_PATH
ROOTSERVER=$LIELAS_PATH/utils/$ROOTBIN
RSPARAMS="-u $USER /var/run/roundup/rootsock"
SERIALBIN=lielas-daemon
SERIALSERVER=/usr/local/bin/$SERIALBIN
SERPARAMS=$LIELAS_PATH
PIDFILE=$RUNDIR/server.pid
ROOTPID=$RUNDIR/handler.pid
SERPID=$RUNDIR/daemon.pid
LOGFILE=$LIELAS_PATH/roundup.log
TRACKERS="lielas=$LIELAS_PATH"
OPTIONS="-- -p 8080 -n 0.0.0.0 -u $USER -d $PIDFILE -l $LOGFILE -t fork $TRACKERS"
NICENESS=0


test -x $EXECUTABLE || exit 0

start_stop() {
	case "$1" in
	start)
		printf "Starting $DESC:"
		start-stop-daemon --start --oknodo --quiet    \
                                  --pidfile $PIDFILE          \
                                  --nicelevel $NICENESS       \
				  --exec $EXECUTABLE $OPTIONS
		printf " $BINFILE"
		start-stop-daemon --start --oknodo --quiet    \
                                  --pidfile $ROOTPID          \
                                  --make-pidfile --background \
                                  --nicelevel $NICENESS       \
				  --exec $ROOTSERVER -- $RSPARAMS
		printf " $ROOTBIN"
		start-stop-daemon --start --oknodo --quiet    \
                                  --pidfile $SERPID           \
                                  --make-pidfile --background \
                                  --nicelevel $NICENESS       \
                                  --chuid $USER               \
				  --exec $SERIALSERVER -- $SERPARAMS
		printf " $SERIALBIN"
		printf ".\n"
		;;
	stop)
		printf "Stopping $DESC:"
		start-stop-daemon --stop --oknodo --quiet     \
                                  --pidfile $PIDFILE
		printf " $BINFILE"
		start-stop-daemon --stop --oknodo --quiet     \
                                  --pidfile $ROOTPID
		printf " $ROOTBIN"
		start-stop-daemon --stop --oknodo --quiet     \
                                  --pidfile $SERPID
		printf " $SERIALBIN"
		printf ".\n"
		;;
	restart | force-reload)
		start_stop stop
		sleep 1
		start_stop start
		;;
	*)
		printf "Usage: $0 {start|stop|restart|force-reload}\n" >&2
		exit 1
		;;
	esac
}

start_stop "$@"

exit 0
